version: '3.8'

services: 
  pay-service:
    build: 
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - PORT=${BACKEND_SERVICE_PORT:-8080}
      - POSTGRES_HOST=${POSTGRES_HOST:-garupa-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-garupa-db}
      - REDIS_HOST=${REDIS_HOST:-garupa-redis} 
      - REDIS_PORT=${REDIS_PORT:-6379}  
    depends_on:
      - garupa-db
      - garupa-redis 
    networks:
      - garupa-network

  garupa-db:
    image: postgres:latest
    container_name: garupa-db
    ports:
      - "${GARUPA_DB_PORT:-5432}:5432"
    environment:
    - POSTGRES_USER=${POSTGRES_USER:-postgres}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    - POSTGRES_DB=${POSTGRES_DB:-garupa-db}
    volumes:
      - garupa-data:/data/db
    networks:
      - garupa-network

  garupa-redis:
    image: redis:latest
    container_name: garupa-redis
    ports:
      - "${REDIS_GARUPA_SERVICE_PORT:-6379}:6379"
    networks:
      - garupa-network
    logging:
      driver: "none"

networks:
  garupa-network:
    driver: bridge

volumes:
  garupa-data: